feat: build for all kernel vers, added overrides for external cap/batt/wakeup-source, added rtc utils

diff --git a/mrhat-rx8130/DEBIAN/postinst b/mrhat-rx8130/DEBIAN/postinst
--- a/mrhat-rx8130/DEBIAN/postinst
+++ b/mrhat-rx8130/DEBIAN/postinst
@@ -4,8 +4,11 @@ then
     echo "blacklist rtc_ds1307" > /etc/modprobe.d/blacklist-rtc_ds1307.conf 
 fi
 
-echo "unloading rtc_ds1307 driver ..."
-rmmod --force rtc_ds1307 || true
+echo "unloading rtc_ds1307 driver if present ..."
+if [[ -n "$(lsmod | grep rtc_ds1307)"  ]];
+then
+    rmmod --force rtc_ds1307 || true
+fi
 
 if [[ -z "$(grep rtc-rx8130 /etc/modules)"  ]];
 then 
@@ -14,17 +17,15 @@ then
     depmod
 fi
 
-if [[ -n "$(lsmod | grep rtc-rx8130)"  ]];
-then
-    echo "Removing already loaded rtc-rx8130 module ..."
-    rmmod --force rtc-rx8130 || true
-fi;
-
-modprobe rtc-rx8130 || echo "failed to load driver module ..."
-
 echo "Adding in dtoverlay to boot config ..."
 grep -qE "^\s*dtoverlay=mrhat-rx8130" /boot/config.txt  ||  echo "dtoverlay=mrhat-rx8130" >> /boot/config.txt
 
-echo "reloading dtoverlay for rtc-rx8130 ..."
-dtoverlay -R mrhat-rx8130 || true
-dtoverlay mrhat-rx8130  || echo "failed to load device tree overlay ... "
+if [[ -n "$(lsmod | grep rtc_rx8130)"  ]];
+then
+    echo "RTC module can't be unloaded when updated, please reboot ... "
+else
+    modprobe rtc-rx8130 || echo "failed to load driver module ..."
+    dtoverlay mrhat-rx8130  || echo "failed to load device tree overlay ... "
+fi;
+
+
